// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdwZtp2cN-D7UbwsBx9nXttPSzSDWky-Q',
    appId: '1:528917038886:web:641bc0667a261f0d9663e7',
    messagingSenderId: '528917038886',
    projectId: 'borrow-3ccfb',
    authDomain: 'borrow-3ccfb.firebaseapp.com',
    storageBucket: 'borrow-3ccfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxABy3hRjk0qi4mdD9EfRb8GEdGz0eRM',
    appId: '1:528917038886:android:62ff45518890ef019663e7',
    messagingSenderId: '528917038886',
    projectId: 'borrow-3ccfb',
    storageBucket: 'borrow-3ccfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF-38N4ZPbPX6KytL1gb5y6STAsPlcWtU',
    appId: '1:528917038886:ios:9f5bf5c2147734429663e7',
    messagingSenderId: '528917038886',
    projectId: 'borrow-3ccfb',
    storageBucket: 'borrow-3ccfb.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF-38N4ZPbPX6KytL1gb5y6STAsPlcWtU',
    appId: '1:528917038886:ios:8786d17b8ab033ce9663e7',
    messagingSenderId: '528917038886',
    projectId: 'borrow-3ccfb',
    storageBucket: 'borrow-3ccfb.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
